# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be095cfa3dc8c139700beb8c740d700a52e9b66beddd467bbbed4c768da5cbdeda707b2e2bee1e56f86aa606ad9ad6a25b2ac7d56604c28252019380bb14faf7

test:
  secret_key_base: 65325cd957cbd52416ac8e9fa7aee28a7aa8f02e6d19ce520ca704a779bd97f69ef088ae8c13ccf8a75f1e590ccc20887b000fbcdfe3ec8b0b3ba52fadbe802f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
